### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by justaCasualCoder** [marcoschulte/lego-wallplotter#3]
Just needed some clarification on a few things:
- Where should the robot's starting position be?
- Should the value in `get_canvas_dim` be the length/width of paper?
- Should the value in `get_canvas_offset` be the length of the ropes from the robot to the anchor when fully unwound?

Thanks!
PS: Great job making the plotter! It is amazing!

**Comment by marcoschulte** [comment]
>     * Where should the robot's starting position be?

The robots starting position should be at the left top of your canvas/paper. This will be the point where it draws, if it draws at (0,0). It's p0 in the figure under "Further improvements: self calibration" on my homepage.

>     * Should the value in `get_canvas_dim` be the length/width of paper?

Yes, kind of. This will be the size of your plot. The top left starting position plus get_canvas_dim is the bottom right corner (it's basically o3 in the figure, p0 = starting pos, p3 = bottom right, p0 + o3 = p3). You probably want your paper to be slightly bigger than this, so you don't accidentally plot on your wall instead of your paper. 

>     * Should the value in `get_canvas_offset` be the length of the ropes from the robot to the anchor when fully unwound?

No. You need to measure from your top left anchor to the starting position of your robot. It's (x0, y0) in the figure

**Comment by justaCasualCoder** [comment]
Thanks for the quick response and explanation! With try to get it working now...

**Comment by justaCasualCoder** [comment]
Got it working! Thanks for your help! I am going to close this now.

**Comment by ghost** [comment]
Hello JustaCasualCoder.

How can I message you? I'm trying out your latest AppImage Scrcpy and I'm running into issues...
You can email me at fltlvl410@pm.me   / if you have time.

Regards,
FLT LVL

**Comment by justaCasualCoder** [comment]
@zookeeper76 

Please create a Issue at https://github.com/justaCasualCoder/Scrcpy-AppImage/issues
